# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        env: # Or as an environment variable
          REACT_APP_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_SPACE_ID }}
          REACT_APP_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      - run: npm ci
      - run: npm ci --prefix frontend
      # - run: npm run build --if-present
      - run: npm test
